---
# all facts for all hosts are gathered; and the common packages
# and configurations are performed on each host.
- name: All
  hosts: all
  roles:
    - common

# provide the control plane
- name: Master
  hosts: master
  gather_facts: no
  vars:
    glusterfs_mode: server
  roles:
    - glusterfs
    - etcd
    - flannel
    - docker
    - kubernetes
    - kubernetes-master
    - addons
    - dnsmasq

# provide the execution plane
- name: Node
  hosts: node
  gather_facts: no
  vars:
    glusterfs_mode: client
  roles:
    - glusterfs
    - flannel
    - docker
    - kubernetes
    - kubernetes-node
    - dnsmasq
