---
- name: create mount point for docker containers
  sudo: yes
  file:
    state: directory
    name: '{{ docker_volume_mount }}'
    recurse: yes
    mode: 0755
  tags:
    - docker
    - volume

- name: format docker container volume
  sudo: yes
  filesystem:
    dev: '{{ docker_volume_device }}'
    fstype: xfs
    opts: '-i size=512'
  tags:
    - docker
    - volume

- name: mount volume for use
  sudo: yes
  mount:
    state: mounted
    name: '{{ docker_volume_mount }}'
    fstype: xfs
    src: '{{ docker_volume_device }}'
    dump: 1
    passno: 2
  tags:
    - docker
    - volume
